CREATE TABLE TB_CURSO
(
    ID_CURSO NUMBER PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DURACAO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,
    PRECO DOUBLE NOT NULL
);
CREATE TABLE TB_CATEGORIA
(
    ID_CATEGORIA   NUMBER PRIMARY KEY,
    NOME_DESCRICAO VARCHAR(50) NOT NULL
);
INSERT INTO TB_CATEGORIA(ID_CATEGORIA,NOME_DESCRICAO)VALUES(1,'Presencial');
INSERT INTO TB_CATEGORIA(ID_CATEGORIA,NOME_DESCRICAO)VALUES(2,'Distancia');
